[package]
name = "someip-payload"
version = "0.1.2"
authors = ["ESRLabs"]
edition = "2021"

[dependencies]
byteorder = "1"
log = "0.4"
quick-xml = "0.23"
regex = "1"
thiserror = "1.0"
ux = "0.1"
voca_rs = "1.14"

[dev-dependencies]
stringreader = "0.1.1"
